# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.update_lightning_automated_transfer_settings import UpdateLightningAutomatedTransferSettings

class TestUpdateLightningAutomatedTransferSettings(unittest.TestCase):
    """UpdateLightningAutomatedTransferSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateLightningAutomatedTransferSettings:
        """Test UpdateLightningAutomatedTransferSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateLightningAutomatedTransferSettings`
        """
        model = UpdateLightningAutomatedTransferSettings()
        if include_optional:
            return UpdateLightningAutomatedTransferSettings(
                interval_seconds = None,
                cancel_payout_after_failures = 1.337,
                process_new_payouts_instantly = True
            )
        else:
            return UpdateLightningAutomatedTransferSettings(
        )
        """

    def testUpdateLightningAutomatedTransferSettings(self):
        """Test UpdateLightningAutomatedTransferSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
