# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from btcpay_greenfield_py.models.basic_app_data import BasicAppData

class TestBasicAppData(unittest.TestCase):
    """BasicAppData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasicAppData:
        """Test BasicAppData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BasicAppData`
        """
        model = BasicAppData()
        if include_optional:
            return BasicAppData(
                id = '3ki4jsAkN4u9rv1PUzj1odX4Nx7s',
                name = 'my test app',
                store_id = '9CiNzKoANXxmk5ayZngSXrHTiVvvgCrwrpFQd4m2K776',
                created = 1651554744,
                app_type = 'PointOfSale',
                archived = True
            )
        else:
            return BasicAppData(
        )
        """

    def testBasicAppData(self):
        """Test BasicAppData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
