# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from btcpay_greenfield_py.models.webhook_data_base import WebhookDataBase

class TestWebhookDataBase(unittest.TestCase):
    """WebhookDataBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDataBase:
        """Test WebhookDataBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDataBase`
        """
        model = WebhookDataBase()
        if include_optional:
            return WebhookDataBase(
                enabled = True,
                automatic_redelivery = True,
                url = '',
                authorized_events = btcpay_greenfield_py.models.webhook_data_base_authorized_events.WebhookDataBase_authorizedEvents(
                    everything = True, 
                    specific_events = [
                        ''
                        ], )
            )
        else:
            return WebhookDataBase(
        )
        """

    def testWebhookDataBase(self):
        """Test WebhookDataBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
