# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from btcpay_greenfield_py.models.payment_status import PaymentStatus

class TestPaymentStatus(unittest.TestCase):
    """PaymentStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentStatus(self):
        """Test PaymentStatus"""
        # inst = PaymentStatus()

if __name__ == '__main__':
    unittest.main()
