# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.custodians_withdraw_from_store_custodian_account403_response import CustodiansWithdrawFromStoreCustodianAccount403Response

class TestCustodiansWithdrawFromStoreCustodianAccount403Response(unittest.TestCase):
    """CustodiansWithdrawFromStoreCustodianAccount403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustodiansWithdrawFromStoreCustodianAccount403Response:
        """Test CustodiansWithdrawFromStoreCustodianAccount403Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustodiansWithdrawFromStoreCustodianAccount403Response`
        """
        model = CustodiansWithdrawFromStoreCustodianAccount403Response()
        if include_optional:
            return CustodiansWithdrawFromStoreCustodianAccount403Response(
            )
        else:
            return CustodiansWithdrawFromStoreCustodianAccount403Response(
        )
        """

    def testCustodiansWithdrawFromStoreCustodianAccount403Response(self):
        """Test CustodiansWithdrawFromStoreCustodianAccount403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
