# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from btcpay_greenfield_py.models.store_on_chain_payment_methods_poston_chain_payment_method_preview_request import StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest

class TestStoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest(unittest.TestCase):
    """StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest:
        """Test StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest`
        """
        model = StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest()
        if include_optional:
            return StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest(
                derivation_scheme = 'xpub...'
            )
        else:
            return StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest(
        )
        """

    def testStoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest(self):
        """Test StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
