# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_users_create_user(self) -> None:
        """Test case for users_create_user

        Create user
        """
        pass

    def test_users_delete_current_user(self) -> None:
        """Test case for users_delete_current_user

        Deletes user profile
        """
        pass

    def test_users_delete_user(self) -> None:
        """Test case for users_delete_user

        Delete user
        """
        pass

    def test_users_get_current_user(self) -> None:
        """Test case for users_get_current_user

        Get current user information
        """
        pass

    def test_users_get_user(self) -> None:
        """Test case for users_get_user

        Get user by ID or Email
        """
        pass

    def test_users_get_users(self) -> None:
        """Test case for users_get_users

        Get all users
        """
        pass

    def test_users_toggle_user_lock(self) -> None:
        """Test case for users_toggle_user_lock

        Toggle user
        """
        pass


if __name__ == '__main__':
    unittest.main()
