# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from btcpay_greenfield_py.api.payment_requests_api import PaymentRequestsApi


class TestPaymentRequestsApi(unittest.TestCase):
    """PaymentRequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentRequestsApi()

    def tearDown(self) -> None:
        pass

    def test_payment_requests_archive_payment_request(self) -> None:
        """Test case for payment_requests_archive_payment_request

        Archive payment request
        """
        pass

    def test_payment_requests_create_payment_request(self) -> None:
        """Test case for payment_requests_create_payment_request

        Create a new payment request
        """
        pass

    def test_payment_requests_get_payment_request(self) -> None:
        """Test case for payment_requests_get_payment_request

        Get payment request
        """
        pass

    def test_payment_requests_get_payment_requests(self) -> None:
        """Test case for payment_requests_get_payment_requests

        Get payment requests
        """
        pass

    def test_payment_requests_pay(self) -> None:
        """Test case for payment_requests_pay

        Create a new invoice for the payment request
        """
        pass

    def test_payment_requests_update_payment_request(self) -> None:
        """Test case for payment_requests_update_payment_request

        Update payment request
        """
        pass


if __name__ == '__main__':
    unittest.main()
