# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.on_chain_wallet_address_data import OnChainWalletAddressData

class TestOnChainWalletAddressData(unittest.TestCase):
    """OnChainWalletAddressData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnChainWalletAddressData:
        """Test OnChainWalletAddressData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnChainWalletAddressData`
        """
        model = OnChainWalletAddressData()
        if include_optional:
            return OnChainWalletAddressData(
                address = '',
                key_path = '',
                payment_link = ''
            )
        else:
            return OnChainWalletAddressData(
        )
        """

    def testOnChainWalletAddressData(self):
        """Test OnChainWalletAddressData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
