# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.lnurl_pay_payment_method_base_data import LNURLPayPaymentMethodBaseData

class TestLNURLPayPaymentMethodBaseData(unittest.TestCase):
    """LNURLPayPaymentMethodBaseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LNURLPayPaymentMethodBaseData:
        """Test LNURLPayPaymentMethodBaseData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LNURLPayPaymentMethodBaseData`
        """
        model = LNURLPayPaymentMethodBaseData()
        if include_optional:
            return LNURLPayPaymentMethodBaseData(
                use_bech32_scheme = True,
                lud12_enabled = True
            )
        else:
            return LNURLPayPaymentMethodBaseData(
        )
        """

    def testLNURLPayPaymentMethodBaseData(self):
        """Test LNURLPayPaymentMethodBaseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
