# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.lightning_internal_node_api import LightningInternalNodeApi


class TestLightningInternalNodeApi(unittest.TestCase):
    """LightningInternalNodeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LightningInternalNodeApi()

    def tearDown(self) -> None:
        pass

    def test_internal_lightning_node_api_connect_to_node(self) -> None:
        """Test case for internal_lightning_node_api_connect_to_node

        Connect to lightning node
        """
        pass

    def test_internal_lightning_node_api_create_invoice(self) -> None:
        """Test case for internal_lightning_node_api_create_invoice

        Create lightning invoice
        """
        pass

    def test_internal_lightning_node_api_get_balance(self) -> None:
        """Test case for internal_lightning_node_api_get_balance

        Get node balance
        """
        pass

    def test_internal_lightning_node_api_get_channels(self) -> None:
        """Test case for internal_lightning_node_api_get_channels

        Get channels
        """
        pass

    def test_internal_lightning_node_api_get_deposit_address(self) -> None:
        """Test case for internal_lightning_node_api_get_deposit_address

        Get deposit address
        """
        pass

    def test_internal_lightning_node_api_get_info(self) -> None:
        """Test case for internal_lightning_node_api_get_info

        Get node information
        """
        pass

    def test_internal_lightning_node_api_get_invoice(self) -> None:
        """Test case for internal_lightning_node_api_get_invoice

        Get invoice
        """
        pass

    def test_internal_lightning_node_api_get_invoices(self) -> None:
        """Test case for internal_lightning_node_api_get_invoices

        Get invoices
        """
        pass

    def test_internal_lightning_node_api_get_payment(self) -> None:
        """Test case for internal_lightning_node_api_get_payment

        Get payment
        """
        pass

    def test_internal_lightning_node_api_get_payments(self) -> None:
        """Test case for internal_lightning_node_api_get_payments

        Get payments
        """
        pass

    def test_internal_lightning_node_api_open_channel(self) -> None:
        """Test case for internal_lightning_node_api_open_channel

        Open channel
        """
        pass

    def test_internal_lightning_node_api_pay_invoice(self) -> None:
        """Test case for internal_lightning_node_api_pay_invoice

        Pay Lightning Invoice
        """
        pass


if __name__ == '__main__':
    unittest.main()
