# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from btcpay_greenfield_py.api.stores_rates_api import StoresRatesApi


class TestStoresRatesApi(unittest.TestCase):
    """StoresRatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StoresRatesApi()

    def tearDown(self) -> None:
        pass

    def test_stores_get_store_rates(self) -> None:
        """Test case for stores_get_store_rates

        Get rates
        """
        pass


if __name__ == '__main__':
    unittest.main()
