# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from btcpay_greenfield_py.models.on_chain_wallet_object_id import OnChainWalletObjectId

class TestOnChainWalletObjectId(unittest.TestCase):
    """OnChainWalletObjectId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OnChainWalletObjectId:
        """Test OnChainWalletObjectId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OnChainWalletObjectId`
        """
        model = OnChainWalletObjectId()
        if include_optional:
            return OnChainWalletObjectId(
                type = '',
                id = ''
            )
        else:
            return OnChainWalletObjectId(
        )
        """

    def testOnChainWalletObjectId(self):
        """Test OnChainWalletObjectId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
