# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from btcpay_greenfield_py.models.invoice_data_base_checkout import InvoiceDataBaseCheckout
from btcpay_greenfield_py.models.invoice_data_base_receipt import InvoiceDataBaseReceipt
from btcpay_greenfield_py.models.invoice_metadata import InvoiceMetadata
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateInvoiceRequest(BaseModel):
    """
    CreateInvoiceRequest
    """ # noqa: E501
    metadata: Optional[InvoiceMetadata] = None
    checkout: Optional[InvoiceDataBaseCheckout] = None
    receipt: Optional[InvoiceDataBaseReceipt] = None
    amount: Optional[StrictStr] = Field(default=None, description="The amount of the invoice. If null or unspecified, the invoice will be a top-up invoice. (ie. The invoice will consider any payment as a full payment)")
    currency: Optional[StrictStr] = Field(default=None, description="The currency of the invoice (if null, empty or unspecified, the currency will be the store's settings default)'")
    additional_search_terms: Optional[List[StrictStr]] = Field(default=None, description="Additional search term to help you find this invoice via text search", alias="additionalSearchTerms")
    __properties: ClassVar[List[str]] = ["metadata", "checkout", "receipt", "amount", "currency", "additionalSearchTerms"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateInvoiceRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of checkout
        if self.checkout:
            _dict['checkout'] = self.checkout.to_dict()
        # override the default output from pydantic by calling `to_dict()` of receipt
        if self.receipt:
            _dict['receipt'] = self.receipt.to_dict()
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if checkout (nullable) is None
        # and model_fields_set contains the field
        if self.checkout is None and "checkout" in self.model_fields_set:
            _dict['checkout'] = None

        # set to None if receipt (nullable) is None
        # and model_fields_set contains the field
        if self.receipt is None and "receipt" in self.model_fields_set:
            _dict['receipt'] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if additional_search_terms (nullable) is None
        # and model_fields_set contains the field
        if self.additional_search_terms is None and "additional_search_terms" in self.model_fields_set:
            _dict['additionalSearchTerms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateInvoiceRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metadata": InvoiceMetadata.from_dict(obj.get("metadata")) if obj.get("metadata") is not None else None,
            "checkout": InvoiceDataBaseCheckout.from_dict(obj.get("checkout")) if obj.get("checkout") is not None else None,
            "receipt": InvoiceDataBaseReceipt.from_dict(obj.get("receipt")) if obj.get("receipt") is not None else None,
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "additionalSearchTerms": obj.get("additionalSearchTerms")
        })
        return _obj


