# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InvoicePaymentMethodDataModelAdditionalDataAnyOf(BaseModel):
    """
    LNURL Pay information
    """ # noqa: E501
    provided_comment: Optional[StrictStr] = Field(default=None, description="The provided comment to a LNUrl payment with comments enabled", alias="providedComment")
    consumed_lightning_address: Optional[StrictStr] = Field(default=None, description="The consumed lightning address of a LN Address payment", alias="consumedLightningAddress")
    __properties: ClassVar[List[str]] = ["providedComment", "consumedLightningAddress"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InvoicePaymentMethodDataModelAdditionalDataAnyOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if provided_comment (nullable) is None
        # and model_fields_set contains the field
        if self.provided_comment is None and "provided_comment" in self.model_fields_set:
            _dict['providedComment'] = None

        # set to None if consumed_lightning_address (nullable) is None
        # and model_fields_set contains the field
        if self.consumed_lightning_address is None and "consumed_lightning_address" in self.model_fields_set:
            _dict['consumedLightningAddress'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InvoicePaymentMethodDataModelAdditionalDataAnyOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "providedComment": obj.get("providedComment"),
            "consumedLightningAddress": obj.get("consumedLightningAddress")
        })
        return _obj


