from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.payment_request_data_status import PaymentRequestDataStatus
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.payment_request_base_data_form_response_type_0 import PaymentRequestBaseDataFormResponseType0


T = TypeVar("T", bound="PaymentRequestData")


@_attrs_define
class PaymentRequestData:
    """
    Attributes:
        amount (str | Unset): The amount of the payment request
        title (str | Unset): The title of the payment request
        currency (None | str | Unset): The currency of the payment request. If empty, the store's default currency code
            will be used.
        email (None | str | Unset): The email used in invoices generated by the payment request
        description (None | str | Unset): The description of the payment request
        expiry_date (float | None | Unset): The expiry date of the payment request
        embedded_css (None | str | Unset): Custom CSS styling for the payment request
        custom_css_link (None | str | Unset): Custom CSS link for styling the payment request
        allow_custom_payment_amounts (bool | None | Unset): Whether to allow users to create invoices that partially pay
            the payment request
        form_id (None | str | Unset): Form ID to request customer data
        form_response (None | PaymentRequestBaseDataFormResponseType0 | Unset): Form data response
        id (str | Unset): The id of the payment request
        store_id (str | Unset): The store identifier that the payment request belongs to
        status (PaymentRequestDataStatus | Unset): The status of the payment request
        created_time (float | Unset): A unix timestamp in seconds Example: 1592312018.
    """

    amount: str | Unset = UNSET
    title: str | Unset = UNSET
    currency: None | str | Unset = UNSET
    email: None | str | Unset = UNSET
    description: None | str | Unset = UNSET
    expiry_date: float | None | Unset = UNSET
    embedded_css: None | str | Unset = UNSET
    custom_css_link: None | str | Unset = UNSET
    allow_custom_payment_amounts: bool | None | Unset = UNSET
    form_id: None | str | Unset = UNSET
    form_response: None | PaymentRequestBaseDataFormResponseType0 | Unset = UNSET
    id: str | Unset = UNSET
    store_id: str | Unset = UNSET
    status: PaymentRequestDataStatus | Unset = UNSET
    created_time: float | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.payment_request_base_data_form_response_type_0 import PaymentRequestBaseDataFormResponseType0

        amount = self.amount

        title = self.title

        currency: None | str | Unset
        if isinstance(self.currency, Unset):
            currency = UNSET
        else:
            currency = self.currency

        email: None | str | Unset
        if isinstance(self.email, Unset):
            email = UNSET
        else:
            email = self.email

        description: None | str | Unset
        if isinstance(self.description, Unset):
            description = UNSET
        else:
            description = self.description

        expiry_date: float | None | Unset
        if isinstance(self.expiry_date, Unset):
            expiry_date = UNSET
        else:
            expiry_date = self.expiry_date

        embedded_css: None | str | Unset
        if isinstance(self.embedded_css, Unset):
            embedded_css = UNSET
        else:
            embedded_css = self.embedded_css

        custom_css_link: None | str | Unset
        if isinstance(self.custom_css_link, Unset):
            custom_css_link = UNSET
        else:
            custom_css_link = self.custom_css_link

        allow_custom_payment_amounts: bool | None | Unset
        if isinstance(self.allow_custom_payment_amounts, Unset):
            allow_custom_payment_amounts = UNSET
        else:
            allow_custom_payment_amounts = self.allow_custom_payment_amounts

        form_id: None | str | Unset
        if isinstance(self.form_id, Unset):
            form_id = UNSET
        else:
            form_id = self.form_id

        form_response: dict[str, Any] | None | Unset
        if isinstance(self.form_response, Unset):
            form_response = UNSET
        elif isinstance(self.form_response, PaymentRequestBaseDataFormResponseType0):
            form_response = self.form_response.to_dict()
        else:
            form_response = self.form_response

        id = self.id

        store_id = self.store_id

        status: str | Unset = UNSET
        if not isinstance(self.status, Unset):
            status = self.status.value

        created_time = self.created_time

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if amount is not UNSET:
            field_dict["amount"] = amount
        if title is not UNSET:
            field_dict["title"] = title
        if currency is not UNSET:
            field_dict["currency"] = currency
        if email is not UNSET:
            field_dict["email"] = email
        if description is not UNSET:
            field_dict["description"] = description
        if expiry_date is not UNSET:
            field_dict["expiryDate"] = expiry_date
        if embedded_css is not UNSET:
            field_dict["embeddedCSS"] = embedded_css
        if custom_css_link is not UNSET:
            field_dict["customCSSLink"] = custom_css_link
        if allow_custom_payment_amounts is not UNSET:
            field_dict["allowCustomPaymentAmounts"] = allow_custom_payment_amounts
        if form_id is not UNSET:
            field_dict["formId"] = form_id
        if form_response is not UNSET:
            field_dict["formResponse"] = form_response
        if id is not UNSET:
            field_dict["id"] = id
        if store_id is not UNSET:
            field_dict["storeId"] = store_id
        if status is not UNSET:
            field_dict["status"] = status
        if created_time is not UNSET:
            field_dict["createdTime"] = created_time

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.payment_request_base_data_form_response_type_0 import PaymentRequestBaseDataFormResponseType0

        d = dict(src_dict)
        amount = d.pop("amount", UNSET)

        title = d.pop("title", UNSET)

        def _parse_currency(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        currency = _parse_currency(d.pop("currency", UNSET))

        def _parse_email(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        email = _parse_email(d.pop("email", UNSET))

        def _parse_description(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        description = _parse_description(d.pop("description", UNSET))

        def _parse_expiry_date(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        expiry_date = _parse_expiry_date(d.pop("expiryDate", UNSET))

        def _parse_embedded_css(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        embedded_css = _parse_embedded_css(d.pop("embeddedCSS", UNSET))

        def _parse_custom_css_link(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        custom_css_link = _parse_custom_css_link(d.pop("customCSSLink", UNSET))

        def _parse_allow_custom_payment_amounts(data: object) -> bool | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(bool | None | Unset, data)

        allow_custom_payment_amounts = _parse_allow_custom_payment_amounts(d.pop("allowCustomPaymentAmounts", UNSET))

        def _parse_form_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        form_id = _parse_form_id(d.pop("formId", UNSET))

        def _parse_form_response(data: object) -> None | PaymentRequestBaseDataFormResponseType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                form_response_type_0 = PaymentRequestBaseDataFormResponseType0.from_dict(data)

                return form_response_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | PaymentRequestBaseDataFormResponseType0 | Unset, data)

        form_response = _parse_form_response(d.pop("formResponse", UNSET))

        id = d.pop("id", UNSET)

        store_id = d.pop("storeId", UNSET)

        _status = d.pop("status", UNSET)
        status: PaymentRequestDataStatus | Unset
        if isinstance(_status, Unset):
            status = UNSET
        else:
            status = PaymentRequestDataStatus(_status)

        created_time = d.pop("createdTime", UNSET)

        payment_request_data = cls(
            amount=amount,
            title=title,
            currency=currency,
            email=email,
            description=description,
            expiry_date=expiry_date,
            embedded_css=embedded_css,
            custom_css_link=custom_css_link,
            allow_custom_payment_amounts=allow_custom_payment_amounts,
            form_id=form_id,
            form_response=form_response,
            id=id,
            store_id=store_id,
            status=status,
            created_time=created_time,
        )

        payment_request_data.additional_properties = d
        return payment_request_data

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
