from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..types import UNSET, Unset

T = TypeVar("T", bound="StoreRateConfiguration")


@_attrs_define
class StoreRateConfiguration:
    """
    Attributes:
        spread (str | Unset): A spread applies to the rate fetched in `%`. Must be `>= 0` or `<= 100`
        preferred_source (str | Unset): If `isCustomerScript` is `false` affect use this source in the default's
            `effectiveScript`, if `isCustomerScript` is `false`, this setting is set to `null`. (See /misc/rate-sources for
            the available sources)
        is_custom_script (bool | Unset): Whether to use `preferredSource` with default script or a custom
            `effectiveScript`.
        effective_script (str | Unset): When `isCustomScript` is `true`, this represent the custom script used to
            calculate a currency pair's exchange rate. Else, it represent the script generated by the default rules and
            `preferredSource`.
    """

    spread: str | Unset = UNSET
    preferred_source: str | Unset = UNSET
    is_custom_script: bool | Unset = UNSET
    effective_script: str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        spread = self.spread

        preferred_source = self.preferred_source

        is_custom_script = self.is_custom_script

        effective_script = self.effective_script

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if spread is not UNSET:
            field_dict["spread"] = spread
        if preferred_source is not UNSET:
            field_dict["preferredSource"] = preferred_source
        if is_custom_script is not UNSET:
            field_dict["isCustomScript"] = is_custom_script
        if effective_script is not UNSET:
            field_dict["effectiveScript"] = effective_script

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        spread = d.pop("spread", UNSET)

        preferred_source = d.pop("preferredSource", UNSET)

        is_custom_script = d.pop("isCustomScript", UNSET)

        effective_script = d.pop("effectiveScript", UNSET)

        store_rate_configuration = cls(
            spread=spread,
            preferred_source=preferred_source,
            is_custom_script=is_custom_script,
            effective_script=effective_script,
        )

        return store_rate_configuration
