# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.application_server_info_node_status_data import ApplicationServerInfoNodeStatusData
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ApplicationServerInfoSyncStatusData(BaseModel):
    """
    Detailed sync status
    """ # noqa: E501
    crypto_code: Optional[StrictStr] = Field(default=None, description="The CryptoCode of the crypto currency (eg. BTC)", alias="cryptoCode")
    node_information: Optional[ApplicationServerInfoNodeStatusData] = Field(default=None, alias="nodeInformation")
    chain_height: Optional[StrictInt] = Field(default=None, description="The height of the chain of header of the internal indexer", alias="chainHeight")
    sync_height: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The height of the latest indexed block of the internal indexer", alias="syncHeight")
    available: Optional[StrictBool] = Field(default=None, description="True if the full node and the indexer are fully synchronized")
    __properties: ClassVar[List[str]] = ["cryptoCode", "nodeInformation", "chainHeight", "syncHeight", "available"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApplicationServerInfoSyncStatusData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of node_information
        if self.node_information:
            _dict['nodeInformation'] = self.node_information.to_dict()
        # set to None if node_information (nullable) is None
        # and model_fields_set contains the field
        if self.node_information is None and "node_information" in self.model_fields_set:
            _dict['nodeInformation'] = None

        # set to None if sync_height (nullable) is None
        # and model_fields_set contains the field
        if self.sync_height is None and "sync_height" in self.model_fields_set:
            _dict['syncHeight'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ApplicationServerInfoSyncStatusData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cryptoCode": obj.get("cryptoCode"),
            "nodeInformation": ApplicationServerInfoNodeStatusData.from_dict(obj.get("nodeInformation")) if obj.get("nodeInformation") is not None else None,
            "chainHeight": obj.get("chainHeight"),
            "syncHeight": obj.get("syncHeight"),
            "available": obj.get("available")
        })
        return _obj


