# coding: utf-8

"""
    BTCPay Greenfield API

    A full API to use your BTCPay Server

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import io
import warnings

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Dict, List, Optional, Tuple, Union, Any

try:
    from typing import Annotated
except ImportError:
    from typing_extensions import Annotated

from pydantic import Field
from typing_extensions import Annotated
from pydantic import StrictBool, StrictFloat, StrictInt, StrictStr

from typing import List, Optional, Union

from btcpay_greenfield_py.models.generate_on_chain_wallet_request import GenerateOnChainWalletRequest
from btcpay_greenfield_py.models.on_chain_payment_method_data import OnChainPaymentMethodData
from btcpay_greenfield_py.models.on_chain_payment_method_data_with_sensitive_data import OnChainPaymentMethodDataWithSensitiveData
from btcpay_greenfield_py.models.on_chain_payment_method_preview_result_data import OnChainPaymentMethodPreviewResultData
from btcpay_greenfield_py.models.store_on_chain_payment_methods_poston_chain_payment_method_preview_request import StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest
from btcpay_greenfield_py.models.update_on_chain_payment_method_request import UpdateOnChainPaymentMethodRequest

from btcpay_greenfield_py.api_client import ApiClient
from btcpay_greenfield_py.api_response import ApiResponse
from btcpay_greenfield_py.rest import RESTResponseType


class StorePaymentMethodsOnChainApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def store_on_chain_payment_methods_delete_on_chain_payment_method(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Remove store on-chain payment method

        Removes the specified store payment method.

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_delete_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_delete_on_chain_payment_method_with_http_info(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Remove store on-chain payment method

        Removes the specified store payment method.

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_delete_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_delete_on_chain_payment_method_without_preload_content(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Remove store on-chain payment method

        Removes the specified store payment method.

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_delete_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_delete_on_chain_payment_method_serialize(
        self,
        crypto_code,
        store_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if crypto_code is not None:
            _path_params['cryptoCode'] = crypto_code
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def store_on_chain_payment_methods_generate_on_chain_wallet(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        generate_on_chain_wallet_request: GenerateOnChainWalletRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> OnChainPaymentMethodDataWithSensitiveData:
        """Generate store on-chain wallet

        Generate a wallet and update the specified store's payment method to it

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param generate_on_chain_wallet_request: (required)
        :type generate_on_chain_wallet_request: GenerateOnChainWalletRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_generate_on_chain_wallet_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            generate_on_chain_wallet_request=generate_on_chain_wallet_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodDataWithSensitiveData",
            '400': "List[ValidationProblemDetailsInner]",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_generate_on_chain_wallet_with_http_info(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        generate_on_chain_wallet_request: GenerateOnChainWalletRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[OnChainPaymentMethodDataWithSensitiveData]:
        """Generate store on-chain wallet

        Generate a wallet and update the specified store's payment method to it

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param generate_on_chain_wallet_request: (required)
        :type generate_on_chain_wallet_request: GenerateOnChainWalletRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_generate_on_chain_wallet_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            generate_on_chain_wallet_request=generate_on_chain_wallet_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodDataWithSensitiveData",
            '400': "List[ValidationProblemDetailsInner]",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_generate_on_chain_wallet_without_preload_content(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        generate_on_chain_wallet_request: GenerateOnChainWalletRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Generate store on-chain wallet

        Generate a wallet and update the specified store's payment method to it

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param generate_on_chain_wallet_request: (required)
        :type generate_on_chain_wallet_request: GenerateOnChainWalletRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_generate_on_chain_wallet_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            generate_on_chain_wallet_request=generate_on_chain_wallet_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodDataWithSensitiveData",
            '400': "List[ValidationProblemDetailsInner]",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_generate_on_chain_wallet_serialize(
        self,
        crypto_code,
        store_id,
        generate_on_chain_wallet_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if crypto_code is not None:
            _path_params['cryptoCode'] = crypto_code
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if generate_on_chain_wallet_request is not None:
            _body_params = generate_on_chain_wallet_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}/generate',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_method(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> OnChainPaymentMethodData:
        """Get store on-chain payment method

        View information about the specified payment method

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_method_with_http_info(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[OnChainPaymentMethodData]:
        """Get store on-chain payment method

        View information about the specified payment method

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_method_without_preload_content(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get store on-chain payment method

        View information about the specified payment method

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_get_on_chain_payment_method_serialize(
        self,
        crypto_code,
        store_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if crypto_code is not None:
            _path_params['cryptoCode'] = crypto_code
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_method_preview(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="From which index to fetch the addresses")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Number of addresses to preview")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> OnChainPaymentMethodPreviewResultData:
        """Preview store on-chain payment method addresses

        View addresses of the current payment method of the store

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param offset: From which index to fetch the addresses
        :type offset: float
        :param amount: Number of addresses to preview
        :type amount: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_method_preview_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            offset=offset,
            amount=amount,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodPreviewResultData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_method_preview_with_http_info(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="From which index to fetch the addresses")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Number of addresses to preview")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[OnChainPaymentMethodPreviewResultData]:
        """Preview store on-chain payment method addresses

        View addresses of the current payment method of the store

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param offset: From which index to fetch the addresses
        :type offset: float
        :param amount: Number of addresses to preview
        :type amount: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_method_preview_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            offset=offset,
            amount=amount,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodPreviewResultData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_method_preview_without_preload_content(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="From which index to fetch the addresses")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Number of addresses to preview")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Preview store on-chain payment method addresses

        View addresses of the current payment method of the store

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param offset: From which index to fetch the addresses
        :type offset: float
        :param amount: Number of addresses to preview
        :type amount: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_method_preview_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            offset=offset,
            amount=amount,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodPreviewResultData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_get_on_chain_payment_method_preview_serialize(
        self,
        crypto_code,
        store_id,
        offset,
        amount,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if crypto_code is not None:
            _path_params['cryptoCode'] = crypto_code
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if amount is not None:
            
            _query_params.append(('amount', amount))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/stores/{storeId}/payment-methods/OnChain/{cryptoCode}/preview',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_methods(
        self,
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        enabled: Annotated[Optional[StrictBool], Field(description="Fetch payment methods that are enabled/disabled only")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[OnChainPaymentMethodData]:
        """Get store on-chain payment methods

        View information about the stores' configured on-chain payment methods

        :param store_id: The store to fetch (required)
        :type store_id: str
        :param enabled: Fetch payment methods that are enabled/disabled only
        :type enabled: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_methods_serialize(
            store_id=store_id,
            enabled=enabled,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[OnChainPaymentMethodData]",
            '401': "ProblemDetails",
            
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_methods_with_http_info(
        self,
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        enabled: Annotated[Optional[StrictBool], Field(description="Fetch payment methods that are enabled/disabled only")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[OnChainPaymentMethodData]]:
        """Get store on-chain payment methods

        View information about the stores' configured on-chain payment methods

        :param store_id: The store to fetch (required)
        :type store_id: str
        :param enabled: Fetch payment methods that are enabled/disabled only
        :type enabled: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_methods_serialize(
            store_id=store_id,
            enabled=enabled,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[OnChainPaymentMethodData]",
            '401': "ProblemDetails",
            
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_get_on_chain_payment_methods_without_preload_content(
        self,
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        enabled: Annotated[Optional[StrictBool], Field(description="Fetch payment methods that are enabled/disabled only")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get store on-chain payment methods

        View information about the stores' configured on-chain payment methods

        :param store_id: The store to fetch (required)
        :type store_id: str
        :param enabled: Fetch payment methods that are enabled/disabled only
        :type enabled: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_get_on_chain_payment_methods_serialize(
            store_id=store_id,
            enabled=enabled,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[OnChainPaymentMethodData]",
            '401': "ProblemDetails",
            
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_get_on_chain_payment_methods_serialize(
        self,
        store_id,
        enabled,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        if enabled is not None:
            
            _query_params.append(('enabled', enabled))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/stores/{storeId}/payment-methods/OnChain',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def store_on_chain_payment_methods_poston_chain_payment_method_preview(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        store_on_chain_payment_methods_poston_chain_payment_method_preview_request: StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest,
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="From which index to fetch the addresses")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Number of addresses to preview")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> OnChainPaymentMethodPreviewResultData:
        """Preview proposed store on-chain payment method addresses

        View addresses of a proposed payment method of the store

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param store_on_chain_payment_methods_poston_chain_payment_method_preview_request: (required)
        :type store_on_chain_payment_methods_poston_chain_payment_method_preview_request: StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest
        :param offset: From which index to fetch the addresses
        :type offset: float
        :param amount: Number of addresses to preview
        :type amount: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_poston_chain_payment_method_preview_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            store_on_chain_payment_methods_poston_chain_payment_method_preview_request=store_on_chain_payment_methods_poston_chain_payment_method_preview_request,
            offset=offset,
            amount=amount,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodPreviewResultData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_poston_chain_payment_method_preview_with_http_info(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        store_on_chain_payment_methods_poston_chain_payment_method_preview_request: StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest,
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="From which index to fetch the addresses")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Number of addresses to preview")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[OnChainPaymentMethodPreviewResultData]:
        """Preview proposed store on-chain payment method addresses

        View addresses of a proposed payment method of the store

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param store_on_chain_payment_methods_poston_chain_payment_method_preview_request: (required)
        :type store_on_chain_payment_methods_poston_chain_payment_method_preview_request: StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest
        :param offset: From which index to fetch the addresses
        :type offset: float
        :param amount: Number of addresses to preview
        :type amount: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_poston_chain_payment_method_preview_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            store_on_chain_payment_methods_poston_chain_payment_method_preview_request=store_on_chain_payment_methods_poston_chain_payment_method_preview_request,
            offset=offset,
            amount=amount,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodPreviewResultData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_poston_chain_payment_method_preview_without_preload_content(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to fetch")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        store_on_chain_payment_methods_poston_chain_payment_method_preview_request: StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest,
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="From which index to fetch the addresses")] = None,
        amount: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Number of addresses to preview")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Preview proposed store on-chain payment method addresses

        View addresses of a proposed payment method of the store

        :param crypto_code: The crypto code of the payment method to fetch (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param store_on_chain_payment_methods_poston_chain_payment_method_preview_request: (required)
        :type store_on_chain_payment_methods_poston_chain_payment_method_preview_request: StoreOnChainPaymentMethodsPOSTOnChainPaymentMethodPreviewRequest
        :param offset: From which index to fetch the addresses
        :type offset: float
        :param amount: Number of addresses to preview
        :type amount: float
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_poston_chain_payment_method_preview_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            store_on_chain_payment_methods_poston_chain_payment_method_preview_request=store_on_chain_payment_methods_poston_chain_payment_method_preview_request,
            offset=offset,
            amount=amount,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodPreviewResultData",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_poston_chain_payment_method_preview_serialize(
        self,
        crypto_code,
        store_id,
        store_on_chain_payment_methods_poston_chain_payment_method_preview_request,
        offset,
        amount,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if crypto_code is not None:
            _path_params['cryptoCode'] = crypto_code
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if amount is not None:
            
            _query_params.append(('amount', amount))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if store_on_chain_payment_methods_poston_chain_payment_method_preview_request is not None:
            _body_params = store_on_chain_payment_methods_poston_chain_payment_method_preview_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/stores/{storeId}/payment-methods/OnChain/{cryptoCode}/preview',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def store_on_chain_payment_methods_update_on_chain_payment_method(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        update_on_chain_payment_method_request: UpdateOnChainPaymentMethodRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> OnChainPaymentMethodData:
        """Update store on-chain payment method

        Update the specified store's payment method

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param update_on_chain_payment_method_request: (required)
        :type update_on_chain_payment_method_request: UpdateOnChainPaymentMethodRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_update_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            update_on_chain_payment_method_request=update_on_chain_payment_method_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodData",
            '400': "List[ValidationProblemDetailsInner]",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def store_on_chain_payment_methods_update_on_chain_payment_method_with_http_info(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        update_on_chain_payment_method_request: UpdateOnChainPaymentMethodRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[OnChainPaymentMethodData]:
        """Update store on-chain payment method

        Update the specified store's payment method

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param update_on_chain_payment_method_request: (required)
        :type update_on_chain_payment_method_request: UpdateOnChainPaymentMethodRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_update_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            update_on_chain_payment_method_request=update_on_chain_payment_method_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodData",
            '400': "List[ValidationProblemDetailsInner]",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def store_on_chain_payment_methods_update_on_chain_payment_method_without_preload_content(
        self,
        crypto_code: Annotated[StrictStr, Field(description="The crypto code of the payment method to update")],
        store_id: Annotated[StrictStr, Field(description="The store to fetch")],
        update_on_chain_payment_method_request: UpdateOnChainPaymentMethodRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update store on-chain payment method

        Update the specified store's payment method

        :param crypto_code: The crypto code of the payment method to update (required)
        :type crypto_code: str
        :param store_id: The store to fetch (required)
        :type store_id: str
        :param update_on_chain_payment_method_request: (required)
        :type update_on_chain_payment_method_request: UpdateOnChainPaymentMethodRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._store_on_chain_payment_methods_update_on_chain_payment_method_serialize(
            crypto_code=crypto_code,
            store_id=store_id,
            update_on_chain_payment_method_request=update_on_chain_payment_method_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "OnChainPaymentMethodData",
            '400': "List[ValidationProblemDetailsInner]",
            '403': None,
            '404': None
            
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _store_on_chain_payment_methods_update_on_chain_payment_method_serialize(
        self,
        crypto_code,
        store_id,
        update_on_chain_payment_method_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> Tuple:

        _host = None

        _collection_formats: Dict[str, str] = {
            
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, str] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if crypto_code is not None:
            _path_params['cryptoCode'] = crypto_code
        if store_id is not None:
            _path_params['storeId'] = store_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if update_on_chain_payment_method_request is not None:
            _body_params = update_on_chain_payment_method_request


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'Basic', 
            'API_Key'
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/api/v1/stores/{storeId}/payment-methods/onchain/{cryptoCode}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


